"""
DATE_FORMAT(COLUMN,"%Y-%m") as alias

LIMIT 1

FROM WHERE GROUP BY HAVING SELECT ORDER BY LIMIT

IS NOT NULL
IS NULL

LOWER(COLUMN)

COALESCE(COLUMN,"DEFAULT") AS ALIAS

DISTINCT

MAX(COLUMN)
MIN(COLUMN)

case
    when condition then result
    else result1
end as "columns name"

sub query
    Scalar Subquery
    Multi-value Subquery
    Correlated Subquery
    Non-correlated Subquery

FLOOR, CEIL, TRUNC, ROUND

GROUP BY EXPRESSION
WHERE EXPRESSION
ORDER BY EXPRESSION

EXTRACT(YEAR FROM YM) AS YEAR

CONCAT(MAX(LENGTH),"cm") as "MAX_LENGTH"
SELECT CONCAT('Hello', ' ', 'World') AS Greeting;
Greeting
---------
Hello World
CONCAT(U.CITY," ",U.STREET_ADDRESS1," ",U.STREET_ADDRESS2) AS "전체주소",
CONCAT(LEFT(U.TLNO,3),'-',SUBSTRING(U.TLNO,4,4),'-',RIGHT(U.TLNO,4)) AS "전화번호"

WHERE "Python" IN (SKILL_1,SKILL_2,SKILL_3)

FROM PATIENT AS P
INNER JOIN APPOINTMENT AS A
    ON P.PT_NO = A.PT_NO
INNER JOIN DOCTOR AS D
    ON D.DR_ID = A.MDDR_ID

SELECT ID AS Employee_ID, NAME AS Employee_Name FROM EMPLOYEES_1
UNION
SELECT ID AS Worker_ID, NAME AS Worker_Name FROM EMPLOYEES_2;

MAX(SIZE_OF_COLONY) OVER (PARTITION BY YEAR(DIFFERENTIATION_DATE)) - SIZE_OF_COLONY AS YEAR_DEV,

JOIN ON "=",">=","&" ....

NTILE(4) OVER (ORDER BY COLUMN NAME DESC)

SET @I := -1 
SELECT @I := @I + 1

WITH RECURSIVE AS NAME(
SELECT 0 AS HOUR
UNION ALL
SELECT HOUR + 1 AS HOUR
FROM HOUR
WHERE HOUR < 23
)


"""
