"""

1. CORRELATED SUB QUERY
SELECT
    FP.CATEGORY,
    FP.PRICE AS MAX_PRICE,
    FP.PRODUCT_NAME
FROM
    FOOD_PRODUCT FP
WHERE
    FP.CATEGORY IN ('과자', '국', '김치', '식용유')
    AND
    FP.PRICE = (SELECT
                    MAX(PRICE)
            FROM
                FOOD_PRODUCT
            WHERE
                FP.CATEGORY = CATEGORY)
ORDER BY
    MAX_PRICE DESC

2. WITH AND 
ROW_NUMBER() OVER(PARTITION BY COLUMN),
RANK() OVER (PARTITION BY COLUMN)

WITH FOOD_PRODUCT_RANKS AS (
SELECT
    CATEGORY,
    PRODUCT_NAME,
    PRICE,
    ROW_NUMBER() OVER (PARTITION BY CATEGORY ORDER BY PRICE DESC) AS RANKS
    
FROM
    FOOD_PRODUCT
WHERE
    CATEGORY IN ('과자', '국', '김치', '식용유')
)

SELECT
    CATEGORY,
    PRICE AS MAX_PRICE,
    PRODUCT_NAME
    
FROM
    FOOD_PRODUCT_RANKS
WHERE
    RANKS = 1
ORDER BY
    MAX_PRICE DESC

"""
