"""
1. inner join으로 맥스 스코어 추가
SELECT
    SUM_GRADE.SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM
    HR_EMPLOYEES E
INNER JOIN
    (SELECT
        SUM(SCORE) AS SCORE,
        EMP_NO
    FROM
        HR_GRADE
    GROUP BY
        EMP_NO,YEAR) AS SUM_GRADE
    ON
    E.EMP_NO = SUM_GRADE.EMP_NO
ORDER BY
    SCORE DESC
LIMIT
    1

2. with절 사용
WITH TotalScore AS (
    SELECT 
        EMP_NO, 
        SUM(SCORE) AS SCORE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
)
SELECT 
    TS.SCORE,
    E.EMP_NO,
    E.EMP_NAME,
    E.POSITION,
    E.EMAIL
FROM TotalScore TS
JOIN HR_EMPLOYEES E
    ON TS.EMP_NO = E.EMP_NO
WHERE TS.SCORE = (SELECT MAX(SCORE) FROM TotalScore);
"""
