"""
1. MAX,CASE,CASE
SELECT 
    CAR_ID,
    CASE 
        WHEN MAX(CASE WHEN '2022-10-16' BETWEEN START_DATE AND END_DATE THEN 1 ELSE 0 END) = 1 
             THEN '대여중'
        ELSE '대여 가능'
    END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC;

2.with,distince,left join
WITH CAR_AVAILABLE AS(
SELECT
    DISTINCT CAR_ID,
    "대여중" AS AVAILABILITY
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    "2022-10-16" BETWEEN START_DATE AND END_DATE
ORDER BY
    CAR_ID)
SELECT
    DISTINCT H.CAR_ID,
    COALESCE(A.AVAILABILITY,"대여 가능")
    
FROM
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
LEFT JOIN
    CAR_AVAILABLE A
    ON
    H.CAR_ID = A.CAR_ID
ORDER BY
    H.CAR_ID DESC
"""
