"""
1.LEFT JOIN SPECIFIC LOWS
WITH CAR_DURATION AS (
SELECT
    H.HISTORY_ID,
    C.CAR_ID,
    C.CAR_TYPE,
    C.DAILY_FEE,
    DATEDIFF(END_DATE, START_DATE) + 1 AS DURATION
FROM
    CAR_RENTAL_COMPANY_CAR C
INNER JOIN
    CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    ON
    C.CAR_ID = H.CAR_ID
WHERE
    CAR_TYPE = "트럭"
)
SELECT
    CD.HISTORY_ID,
    CASE
        WHEN CD.DURATION >= 90 THEN FLOOR(CD.DAILY_FEE * (1 - D90.DISCOUNT_RATE/100) * CD.DURATION)
        WHEN CD.DURATION >= 30 THEN FLOOR(CD.DAILY_FEE * (1 - D30.DISCOUNT_RATE/100) * CD.DURATION)
        WHEN CD.DURATION >= 7 THEN FLOOR(CD.DAILY_FEE * (1 - D7.DISCOUNT_RATE/100) * CD.DURATION)
        ELSE FLOOR(CD.DAILY_FEE * CD.DURATION)
    END AS FEE
FROM
    CAR_DURATION CD
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D7 ON CD.CAR_TYPE = D7.CAR_TYPE AND D7.DURATION_TYPE = '7일 이상'
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D30 ON CD.CAR_TYPE = D30.CAR_TYPE AND D30.DURATION_TYPE = '30일 이상'
LEFT JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D90 ON CD.CAR_TYPE = D90.CAR_TYPE AND D90.DURATION_TYPE = '90일 이상'
ORDER BY
    FEE DESC, HISTORY_ID DESC
"""
