"""
1. available time
WITH AVAILABLE_CARS AS (
    SELECT 
        C.CAR_ID, 
        C.CAR_TYPE, 
        C.DAILY_FEE
    FROM 
        CAR_RENTAL_COMPANY_CAR C
    WHERE 
        C.CAR_TYPE IN ('세단', 'SUV')
        AND C.CAR_ID NOT IN (
            SELECT DISTINCT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE (START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01')
        )
)

SELECT 
    A.CAR_ID,
    A.CAR_TYPE,
    FLOOR(A.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE/100)) AS FEE
FROM 
    AVAILABLE_CARS A
JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN D 
    ON A.CAR_TYPE = D.CAR_TYPE AND D.DURATION_TYPE = '30일 이상'
WHERE 
    FLOOR(A.DAILY_FEE * 30 * (1 - D.DISCOUNT_RATE/100)) BETWEEN 500000 AND 1999999
ORDER BY 
    FEE DESC, 
    A.CAR_TYPE ASC, 
    A.CAR_ID DESC;
"""
